<a href="https://colab.research.google.com/github/siddharthaborgohain/Deep-Learning/blob/main/1st%20perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
ROOT="/content/drive/MyDrive"

In [3]:
import os

os.chdir(ROOT)

In [4]:
!ls

 1638698922733.jpg
'afs-fwct-dpt – 17 Jan 2022.gjam'
 BitcoinHeistData.csv
 Capture.JPG
'Colab Notebooks'
'czu-guhm-uov – 6 Aug 2021 (1).gjam'
'czu-guhm-uov – 6 Aug 2021 (2).gjam'
'czu-guhm-uov – 6 Aug 2021 (3).gjam'
'czu-guhm-uov – 6 Aug 2021 (4).gjam'
'czu-guhm-uov – 6 Aug 2021.gjam'
'dja-qxog-ctt – 13 Aug 2021.gjam'
'DS C31 Program Calendar.xlsx'
'fon-rxjr-xgy – 25 Dec 2021 (1).gjam'
'fon-rxjr-xgy – 25 Dec 2021 (2).gjam'
'fon-rxjr-xgy – 25 Dec 2021.gjam'
'gpx-qzch-jrx – 23 Oct 2021 (1).gjam'
'gpx-qzch-jrx – 23 Oct 2021.gjam'
'hcx-cmdu-dro – 13 Aug 2021.gjam'
'Machine Learning A-Z (Codes and Datasets)'
'ncm-zmei-esq – 18 Dec 2021 (1).gjam'
'ncm-zmei-esq – 18 Dec 2021.gjam'
'new Resume_Siddhartha (1).pdf'
'PGDDS March 2021 - C30 Live session Recordings.gsheet'
 Project_Plan_29072021.xlsx
'ryi-gwho-fah – 11 Aug 2021.gjam'
'SIDDHARTHA_BORHOHAIN_Senior_Data_Scientist (1).pdf'
 SIDDHARTHA_BORHOHAIN_Senior_Data_Scientist.pdf
'To-do list.gsheet'
'twibbon-profile (1).png'
 untitled-27-may-20

In [5]:
assert ROOT ==os.getcwd()

In [6]:
os.getcwd()

'/content/drive/MyDrive'

In [7]:
with open("test.txt","w") as f:
  f.writelines("hello colab")

In [8]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import joblib # saving model as binary file
from matplotlib.colors import LinearSegmentedColormap

plt.style.use("fivethirtyeight") # style graph

In [18]:
from re import X
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3)* 1e-4 #SMALL WEIGHT INIT
    print(f"initial weights before training: {self.weights}")
    self.eta = eta #Learning Rate
    self.epochs = epochs
  def activationFunction(self, input, weights):
    z=np.dot(input, weights)
    return np.where(z > 0 ,1,0)
  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
    print(f"X with bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print("--"*10)
      print(f"for epoch:{epoch}")
      print("--"*10)

      y_hat=self.activationFunction(X_with_bias, self.weights)# forward propogation
      print(f"predicted value after forward pass: {y_hat}")
      self.error =self.y-y_hat
      print(f"error:\n{self.error}")

      self.weights=self.weights +self.eta *np.dot(X_with_bias.T,self.error) # BACKWARD PROPAGATION
      print(f"updated weights after epoch: \n{epoch}/{self.epochs} : {self.weights}")
      print("#####"*10)
  def predict(self, X):
    X_with_bias = np.c_[self.X, -np.ones((len(X),1))]
    return self.activationFunction(X_with_bias,self.weights)
  def total_loss(self):
    total_loss = np.sum(self.error)
    print(f"total loss: {total_loss}")
    return total_loss

In [19]:
def prepare_data(df):
  X=df.drop("y",axis=1)
  y=df["y"]
  return X, y

In [20]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1],
}

df = pd.DataFrame(AND)

df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [21]:
X,y =prepare_data(df)

ETA =0.3
EPOCHS=10

model=Perceptron(eta=ETA,epochs=EPOCHS)
model.fit(X,y)

_= model.total_loss()


initial weights before training: [-1.28826722e-04 -3.50894574e-06  1.16841268e-04]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch:0
--------------------
predicted value after forward pass: [0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 
0/10 : [ 0.29987117  0.29999649 -0.29988316]
##################################################
--------------------
for epoch:1
--------------------
predicted value after forward pass: [1 1 1 1]
error:
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 
1/10 : [-1.28826722e-04 -3.50894574e-06  6.00116841e-01]
##################################################
--------------------
for epoch:2
--------------------
predicted value after forward pass: [0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 
2/10 : [0.29987117 0.29999649 0.30011684]
###################################