<a href="https://colab.research.google.com/github/siddharthaborgohain/Deep-Learning/blob/main/Start%20Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Artificial Neural Network


importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.8.0'

**Data Preprocessing**

*Importing the dataset*

In [5]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [22]:
X = dataset.iloc[:,:-1].values

In [23]:
y=dataset.iloc[:,-1].values


In [24]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Splitting the dataset into training set and test set

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=0) 


**Building The ANN**

*initializing the ann *

In [26]:
ann = tf.keras.models.Sequential()

*Adding the input layer and first hidden layer*

In [27]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

*Adding second hidden layer*

In [28]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

*Adding the output layer*

In [29]:
ann.add(tf.keras.layers.Dense(units=1))

**Training the ANN**

*Compiling the ANN*

In [30]:
ann.compile(optimizer='adam',loss= 'mean_squared_error')

*Training the ANN model on trainig set*

In [31]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 16756.0098
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 155.9901
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 147.6592
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 144.8036
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 141.3427
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 137.5177
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 133.2048
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 128.2697
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 123.1328
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 117.5332
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 111.9279
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - lo

*Predicting the result of the Test set*

In [32]:
y_pred=ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)), 1))


[[429.58 431.23]
 [460.79 460.01]
 [464.39 461.14]
 ...
 [471.37 473.26]
 [438.74 438.  ]
 [457.7  463.28]]
